### ISSUE TITLE
Error when using with SSR

### ISSUE THREAD

**Issue by cmseguin** [vuejs/vue-hot-reload-api#59]
```
/Users/cmseguin/dev/git/home-controller/node_modules/vue-hot-reload-api/dist/index.js:3
var map = (window.__VUE_HOT_MAP__ = Object.create(null))
                                  ^

ReferenceError: window is not defined
    at Object.<anonymous> (/Users/cmseguin/dev/git/home-controller/node_modules/vue-hot-reload-api/dist/index.js:3:35)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at $serverRequire (/Users/cmseguin/dev/git/home-controller/dist/server.js:2198:22)
    at $getRef (/Users/cmseguin/dev/git/home-controller/dist/server.js:2230:20)
```

I believe a simple check on the window should fix that issue

**Comment by JohnLouderback** [comment]
@cmseguin Were you able to fix this?

**Comment by davidovich** [comment]
I believe this is fixed in 554ffa3
